database:
  host: mysql
  port: 3306
  username: cutepetpro
  password: YhKiwmATtRJ2Jhme
  database: project4_prod
  charset: utf8mb4

redis:
  host: redis
  port: 6379
  password:
  DB: 0

app:
  port: 8082
  debug: false
  log_level: debug
  secret_key: testsecret
  env: production

email_service:
  host: smtp.163.com
  port: 465
  username: xingtianwuganqi123@163.com
  password: DQHEPDTSYPAVKEFB

api_keys:
  google: test-google-api-key
  facebook: test-facebook-api-key
  qiniuAccessKey: 1vLUgTSJEyyElB_EFpsCzua84QJJqrtrPrueICw2
  qiniuSecretKey : QvOlYbG0my-CGh7nfjnBnOxVP1j3ClqhR1Ocf0Ug